### ISSUE TITLE
Map Schoology Courses to Labels.

### ISSUE THREAD

**Issue by ariporad** [ariporad/todology#1]
I'd like to be able to specify a mapping of schoology courses to labels.

For Example, Given this `config.yml`:

``` yaml
# ...
schoology:
  # ....
  tags:
    665527415: Science
    736804619: French
```

Any event originating from the Schoology course with the ID `736804619` would be labeled with `@French` along with all the other tags.
